set background=dark
if exists('g:colors_name')
hi clear
if exists('syntax_on')
syntax reset
endif
endif
let g:colors_name = 'lushwal'
highlight Normal guifg=#E6E8E3 guibg=#101312 guisp=NONE blend=NONE gui=NONE
highlight! link User Normal
highlight Bold guifg=#E6E8E3 guibg=#101312 guisp=NONE blend=NONE gui=bold
highlight Boolean guifg=#BCC0B5 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Character guifg=#ADB8B3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight ColorColumn guifg=#B5B8B2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Comment guifg=#E6E8E3 guibg=NONE guisp=NONE blend=NONE gui=italic
highlight Conceal guifg=#A1A39F guibg=#101312 guisp=NONE blend=NONE gui=NONE
highlight! link Whitespace Conceal
highlight Conditional guifg=#C9C8DF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Constant guifg=#BCC0B5 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Cursor guifg=#101312 guibg=#E6E8E3 guisp=NONE blend=NONE gui=NONE
highlight CursorColumn guifg=#B5B8B2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight CursorLine guifg=NONE guibg=#A1A39F guisp=NONE blend=NONE gui=NONE
highlight CursorLineNr guifg=#E6E8E3 guibg=#101312 guisp=NONE blend=NONE gui=NONE
highlight Debug guifg=#ADB8B3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Define guifg=#C9C8DF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Delimiter guifg=#AFBBB7 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticError guifg=#ADB8B3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticHint guifg=#CDD5CF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticInfo guifg=#9BC5C2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticUnderlineError guifg=#ADB8B3 guibg=NONE guisp=#ADB8B3 blend=NONE gui=underline
highlight DiagnosticUnderlineHint guifg=#CDD5CF guibg=NONE guisp=#CDD5CF blend=NONE gui=underline
highlight DiagnosticUnderlineInfo guifg=#9BC5C2 guibg=NONE guisp=#9BC5C2 blend=NONE gui=underline
highlight DiagnosticUnderlineWarn guifg=#CBC9B9 guibg=NONE guisp=#CBC9B9 blend=NONE gui=underline
highlight DiagnosticWarn guifg=#CBC9B9 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiffAdd guifg=#B2C2BB guibg=#A1A39F guisp=NONE blend=NONE gui=bold
highlight! link DiffAdded DiffAdd
highlight DiffChange guifg=#CFD1CC guibg=#A1A39F guisp=NONE blend=NONE gui=NONE
highlight DiffDelete guifg=#ADB8B3 guibg=#A1A39F guisp=NONE blend=NONE gui=bold
highlight! link DiffRemoved DiffDelete
highlight! link diffRemoved DiffDelete
highlight DiffFile guifg=#ADB8B3 guibg=#101312 guisp=NONE blend=NONE gui=NONE
highlight DiffLine guifg=#9BC5C2 guibg=#101312 guisp=NONE blend=NONE gui=NONE
highlight DiffNewFile guifg=#B2C2BB guibg=#101312 guisp=NONE blend=NONE gui=NONE
highlight DiffText guifg=#9BC5C2 guibg=#A1A39F guisp=NONE blend=NONE gui=NONE
highlight Directory guifg=#9BC5C2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight EndOfBuffer guifg=#E6E8E3 guibg=#101312 guisp=NONE blend=NONE gui=NONE
highlight Error guifg=#ADB8B3 guibg=#E6E8E3 guisp=NONE blend=NONE gui=NONE
highlight ErrorMsg guifg=#ADB8B3 guibg=#101312 guisp=NONE blend=NONE gui=NONE
highlight Exception guifg=#ADB8B3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Float guifg=#BCC0B5 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight FoldColumn guifg=#9BC5C2 guibg=#101312 guisp=NONE blend=NONE gui=NONE
highlight Folded guifg=#E6E8E3 guibg=#A1A39F guisp=NONE blend=NONE gui=italic
highlight Function guifg=#9BC5C2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Identifier guifg=#CDD5CF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight IncSearch guifg=#A1A39F guibg=#BCC0B5 guisp=NONE blend=NONE gui=NONE
highlight Include guifg=#9BC5C2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Italic guifg=#E6E8E3 guibg=#101312 guisp=NONE blend=NONE gui=italic
highlight Keyword guifg=#C9C8DF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Label guifg=#CBC9B9 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight LineNr guifg=#CFD1CC guibg=#101312 guisp=NONE blend=NONE gui=NONE
highlight Macro guifg=#ADB8B3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MatchParen guifg=#E6E8E3 guibg=#CFD1CC guisp=NONE blend=NONE gui=NONE
highlight MiniCompletionActiveParameter guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniCursorword guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=underline
highlight! link MiniCursorwordCurrent MiniCursorword
highlight MiniIndentscopePrefix guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=nocombine
highlight MiniIndentscopeSymbol guifg=#A1A39F guibg=#101312 guisp=NONE blend=NONE gui=NONE
highlight MiniJump guifg=#9BC5C2 guibg=NONE guisp=#CFD1CC blend=NONE gui=underline
highlight MiniJump2dSpot guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=undercurl
highlight MiniStarterCurrent guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterFooter guifg=#9BC5C2 guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniStarterHeader guifg=#9BC5C2 guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniStarterInactive guifg=#E6E8E3 guibg=NONE guisp=NONE blend=NONE gui=italic
highlight MiniStarterItem guifg=#E6E8E3 guibg=#101312 guisp=NONE blend=NONE gui=NONE
highlight MiniStarterItemBullet guifg=#AFBBB7 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterItemPrefix guifg=#ADB8B3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterQuery guifg=#B2C2BB guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterSection guifg=#AFBBB7 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineDevinfo guifg=#E6E8E3 guibg=#A1A39F guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineFileinfo guifg=#E6E8E3 guibg=#A1A39F guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineFilename guifg=#CBC9B9 guibg=#A1A39F guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineInactive guifg=#B5B8B2 guibg=#A1A39F guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeCommand guifg=#101312 guibg=#CDD5CF guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeInsert guifg=#101312 guibg=#9BC5C2 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeNormal guifg=#101312 guibg=#B2C2BB guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeOther guifg=#101312 guibg=#C9C8DF guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeReplace guifg=#101312 guibg=#ADB8B3 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeVisual guifg=#101312 guibg=#BCC0B5 guisp=NONE blend=NONE gui=NONE
highlight MiniSurround guifg=#A1A39F guibg=#BCC0B5 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineCurrent guifg=#CFD1CC guibg=#A1A39F guisp=NONE blend=NONE gui=NONE
highlight MiniTablineFill guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniTablineHidden guifg=#B2C2BB guibg=#A1A39F guisp=NONE blend=NONE gui=NONE
highlight MiniTablineModifiedCurrent guifg=#E6E8E3 guibg=#A1A39F guisp=NONE blend=NONE gui=NONE
highlight MiniTablineModifiedHidden guifg=#B5B8B2 guibg=#A1A39F guisp=NONE blend=NONE gui=NONE
highlight MiniTablineModifiedVisible guifg=#E6E8E3 guibg=#A1A39F guisp=NONE blend=NONE gui=NONE
highlight MiniTablineVisible guifg=#CFD1CC guibg=#A1A39F guisp=NONE blend=NONE gui=NONE
highlight MiniTestEmphasis guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniTestFail guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniTestPass guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniTrailspace guifg=#ADB8B3 guibg=#E6E8E3 guisp=NONE blend=NONE gui=NONE
highlight ModeMsg guifg=#B2C2BB guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MoreMsg guifg=#B2C2BB guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight NonText guifg=#CFD1CC guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Number guifg=#BCC0B5 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Operator guifg=#E6E8E3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight PMenu guifg=#E6E8E3 guibg=#A1A39F guisp=NONE blend=NONE gui=NONE
highlight PMenuSel guifg=#E6E8E3 guibg=#9BC5C2 guisp=NONE blend=NONE gui=NONE
highlight PmenuSbar guifg=#B5B8B2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight PmenuThumb guifg=#E6E8E3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight PreProc guifg=#CBC9B9 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Question guifg=#9BC5C2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Repeat guifg=#CBC9B9 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Search guifg=#CFD1CC guibg=#CBC9B9 guisp=NONE blend=NONE gui=NONE
highlight! link MiniTablineTabpagesection Search
highlight SignColumn guifg=#B5B8B2 guibg=#101312 guisp=NONE blend=NONE gui=NONE
highlight Special guifg=#CDD5CF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight SpecialChar guifg=#AFBBB7 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight SpecialKey guifg=#CFD1CC guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight SpellBad guifg=#ADB8B3 guibg=NONE guisp=#ADB8B3 blend=NONE gui=underline
highlight SpellCap guifg=#CBC9B9 guibg=NONE guisp=#CBC9B9 blend=NONE gui=underline
highlight SpellLocal guifg=#CDD5CF guibg=NONE guisp=#CDD5CF blend=NONE gui=underline
highlight SpellRare guifg=#C9C8DF guibg=NONE guisp=#C9C8DF blend=NONE gui=underline
highlight Statement guifg=#ADB8B3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight StatusLine guifg=#E6E8E3 guibg=#A1A39F guisp=NONE blend=NONE gui=NONE
highlight StatusLineNC guifg=#B5B8B2 guibg=#A1A39F guisp=NONE blend=NONE gui=NONE
highlight StatusLineTerm guifg=#B2C2BB guibg=#B2C2BB guisp=NONE blend=NONE gui=NONE
highlight StatusLineTermNC guifg=#CBC9B9 guibg=#A1A39F guisp=NONE blend=NONE gui=NONE
highlight StorageClass guifg=#CBC9B9 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight String guifg=#B2C2BB guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Structure guifg=#C9C8DF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight TabLine guifg=#CFD1CC guibg=#A1A39F guisp=NONE blend=NONE gui=NONE
highlight TabLineFill guifg=#CFD1CC guibg=#A1A39F guisp=NONE blend=NONE gui=NONE
highlight TabLineSel guifg=#B2C2BB guibg=#A1A39F guisp=NONE blend=NONE gui=NONE
highlight Tag guifg=#CBC9B9 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Title guifg=#9BC5C2 guibg=NONE guisp=NONE blend=NONE gui=bold
highlight Todo guifg=#CBC9B9 guibg=#A1A39F guisp=NONE blend=NONE gui=NONE
highlight TooLong guifg=#ADB8B3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Type guifg=#CBC9B9 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Typedef guifg=#CBC9B9 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Underlined guifg=#ADB8B3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight VertSplit guifg=#E6E8E3 guibg=#101312 guisp=NONE blend=NONE gui=NONE
highlight! link WinSeparator VertSplit
highlight Visual guifg=#101312 guibg=#B5B8B2 guisp=NONE blend=NONE gui=NONE
highlight VisualNOS guifg=#ADB8B3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight WarningMsg guifg=#ADB8B3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight WildMenu guifg=#E6E8E3 guibg=#9BC5C2 guisp=NONE blend=NONE gui=NONE
highlight WinBar guifg=#E6E8E3 guibg=#101312 guisp=NONE blend=NONE gui=NONE
highlight WinBarNC guifg=#B5B8B2 guibg=#101312 guisp=NONE blend=NONE gui=NONE
highlight gitCommitOverflow guifg=#ADB8B3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight gitCommitSummary guifg=#B2C2BB guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight helpCommand guifg=#CBC9B9 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight helpExample guifg=#CBC9B9 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @attribute guifg=#9BC5C2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @boolean guifg=#9BC5C2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @character guifg=#CBC9B9 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @character.special guifg=#AFBBB7 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @comment guifg=#E6E8E3 guibg=NONE guisp=NONE blend=NONE gui=italic
highlight @conditional guifg=#ADB8B3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constant guifg=#ADB8B3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constant.builtin guifg=#ADB8B3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constant.macro guifg=#ADB8B3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constructor guifg=#E6E8E3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @debug guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @define guifg=#C9C8DF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @exception guifg=#ADB8B3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @field guifg=#B2C2BB guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @float guifg=#9BC5C2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @function guifg=#9BC5C2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @function.builtin guifg=#ADB8B3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @function.macro guifg=#ADB8B3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @include guifg=#CDD5CF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @keyword guifg=#C9C8DF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @keyword.function guifg=#CDD5CF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @keyword.operator guifg=#C9C8DF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @label guifg=#CDD5CF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @method guifg=#9BC5C2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @namespace guifg=#9BC5C2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @none guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @number guifg=#9BC5C2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @operator guifg=#E6E8E3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @parameter guifg=#CBC9B9 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @preproc guifg=#CBC9B9 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @property guifg=#CBC9B9 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @punctuation.bracket guifg=#E6E8E3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @punctuation.delimiter guifg=#E6E8E3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @punctuation.special guifg=#CDD5CF guibg=NONE guisp=NONE blend=NONE gui=bold
highlight @repeat guifg=#ADB8B3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @storageclass guifg=#CBC9B9 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string guifg=#9BC5C2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string.escape guifg=#B2C2BB guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string.regex guifg=#B2C2BB guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string.special guifg=#AFBBB7 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @symbol guifg=#CDD5CF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @tag guifg=#CBC9B9 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @tag.attribute guifg=#CDD5CF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @tag.delimiter guifg=#CDD5CF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text guifg=#B2C2BB guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.bold guifg=#CBC9B9 guibg=NONE guisp=NONE blend=NONE gui=bold
highlight @text.danger guifg=#ADB8B3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.diff.add guifg=#B2C2BB guibg=#A1A39F guisp=NONE blend=NONE gui=bold
highlight @text.diff.delete guifg=#ADB8B3 guibg=#A1A39F guisp=NONE blend=NONE gui=bold
highlight @text.emphasis guifg=#C9C8DF guibg=NONE guisp=NONE blend=NONE gui=italic
highlight @text.environment guifg=#ADB8B3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.environment.name guifg=#CBC9B9 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.literal guifg=#B2C2BB guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.math guifg=#CDD5CF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.note guifg=#CDD5CF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.reference guifg=#ADB8B3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.strike guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=strikethrough
highlight @text.title guifg=#9BC5C2 guibg=NONE guisp=NONE blend=NONE gui=bold
highlight @text.todo guifg=#CBC9B9 guibg=#A1A39F guisp=NONE blend=NONE gui=NONE
highlight @text.underline guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=underline
highlight @text.uri guifg=NONE guibg=#A1A39F guisp=NONE blend=NONE gui=underline
highlight @type guifg=#9BC5C2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @type.builtin guifg=#9BC5C2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @type.definition guifg=#CBC9B9 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @variable guifg=#CBC9B9 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @variable.builtin guifg=#ADB8B3 guibg=NONE guisp=NONE blend=NONE gui=NONE
