set background=dark
if exists('g:colors_name')
hi clear
if exists('syntax_on')
syntax reset
endif
endif
let g:colors_name = 'lushwal'
highlight Normal guifg=#C2C4C7 guibg=#0D1421 guisp=NONE blend=NONE gui=NONE
highlight! link User Normal
highlight Bold guifg=#C2C4C7 guibg=#0D1421 guisp=NONE blend=NONE gui=bold
highlight Boolean guifg=#8F707D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Character guifg=#53586E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight ColorColumn guifg=#7B818E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Comment guifg=#C2C4C7 guibg=NONE guisp=NONE blend=NONE gui=italic
highlight Conceal guifg=#5E6473 guibg=#0D1421 guisp=NONE blend=NONE gui=NONE
highlight! link Whitespace Conceal
highlight Conditional guifg=#9E83C9 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Constant guifg=#8F707D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Cursor guifg=#0D1421 guibg=#C2C4C7 guisp=NONE blend=NONE gui=NONE
highlight CursorColumn guifg=#7B818E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight CursorLine guifg=NONE guibg=#5E6473 guisp=NONE blend=NONE gui=NONE
highlight CursorLineNr guifg=#C2C4C7 guibg=#0D1421 guisp=NONE blend=NONE gui=NONE
highlight Debug guifg=#53586E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Define guifg=#9E83C9 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Delimiter guifg=#555C72 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticError guifg=#53586E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticHint guifg=#6C8699 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticInfo guifg=#3A6D83 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticUnderlineError guifg=#53586E guibg=NONE guisp=#53586E blend=NONE gui=underline
highlight DiagnosticUnderlineHint guifg=#6C8699 guibg=NONE guisp=#6C8699 blend=NONE gui=underline
highlight DiagnosticUnderlineInfo guifg=#3A6D83 guibg=NONE guisp=#3A6D83 blend=NONE gui=underline
highlight DiagnosticUnderlineWarn guifg=#BA7E7D guibg=NONE guisp=#BA7E7D blend=NONE gui=underline
highlight DiagnosticWarn guifg=#BA7E7D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiffAdd guifg=#B6585A guibg=#5E6473 guisp=NONE blend=NONE gui=bold
highlight! link DiffAdded DiffAdd
highlight DiffChange guifg=#9EA2A9 guibg=#5E6473 guisp=NONE blend=NONE gui=NONE
highlight DiffDelete guifg=#53586E guibg=#5E6473 guisp=NONE blend=NONE gui=bold
highlight! link DiffRemoved DiffDelete
highlight! link diffRemoved DiffDelete
highlight DiffFile guifg=#53586E guibg=#0D1421 guisp=NONE blend=NONE gui=NONE
highlight DiffLine guifg=#3A6D83 guibg=#0D1421 guisp=NONE blend=NONE gui=NONE
highlight DiffNewFile guifg=#B6585A guibg=#0D1421 guisp=NONE blend=NONE gui=NONE
highlight DiffText guifg=#3A6D83 guibg=#5E6473 guisp=NONE blend=NONE gui=NONE
highlight Directory guifg=#3A6D83 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight EndOfBuffer guifg=#C2C4C7 guibg=#0D1421 guisp=NONE blend=NONE gui=NONE
highlight Error guifg=#53586E guibg=#C2C4C7 guisp=NONE blend=NONE gui=NONE
highlight ErrorMsg guifg=#53586E guibg=#0D1421 guisp=NONE blend=NONE gui=NONE
highlight Exception guifg=#53586E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Float guifg=#8F707D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight FoldColumn guifg=#3A6D83 guibg=#0D1421 guisp=NONE blend=NONE gui=NONE
highlight Folded guifg=#C2C4C7 guibg=#5E6473 guisp=NONE blend=NONE gui=italic
highlight Function guifg=#3A6D83 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Identifier guifg=#6C8699 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight IncSearch guifg=#5E6473 guibg=#8F707D guisp=NONE blend=NONE gui=NONE
highlight Include guifg=#3A6D83 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Italic guifg=#C2C4C7 guibg=#0D1421 guisp=NONE blend=NONE gui=italic
highlight Keyword guifg=#9E83C9 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Label guifg=#BA7E7D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight LineNr guifg=#9EA2A9 guibg=#0D1421 guisp=NONE blend=NONE gui=NONE
highlight Macro guifg=#53586E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MatchParen guifg=#C2C4C7 guibg=#9EA2A9 guisp=NONE blend=NONE gui=NONE
highlight MiniCompletionActiveParameter guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniCursorword guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=underline
highlight! link MiniCursorwordCurrent MiniCursorword
highlight MiniIndentscopePrefix guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=nocombine
highlight MiniIndentscopeSymbol guifg=#5E6473 guibg=#0D1421 guisp=NONE blend=NONE gui=NONE
highlight MiniJump guifg=#3A6D83 guibg=NONE guisp=#9EA2A9 blend=NONE gui=underline
highlight MiniJump2dSpot guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=undercurl
highlight MiniStarterCurrent guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterFooter guifg=#3A6D83 guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniStarterHeader guifg=#3A6D83 guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniStarterInactive guifg=#C2C4C7 guibg=NONE guisp=NONE blend=NONE gui=italic
highlight MiniStarterItem guifg=#C2C4C7 guibg=#0D1421 guisp=NONE blend=NONE gui=NONE
highlight MiniStarterItemBullet guifg=#555C72 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterItemPrefix guifg=#53586E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterQuery guifg=#B6585A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterSection guifg=#555C72 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineDevinfo guifg=#C2C4C7 guibg=#5E6473 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineFileinfo guifg=#C2C4C7 guibg=#5E6473 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineFilename guifg=#BA7E7D guibg=#5E6473 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineInactive guifg=#7B818E guibg=#5E6473 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeCommand guifg=#0D1421 guibg=#6C8699 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeInsert guifg=#0D1421 guibg=#3A6D83 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeNormal guifg=#0D1421 guibg=#B6585A guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeOther guifg=#0D1421 guibg=#9E83C9 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeReplace guifg=#0D1421 guibg=#53586E guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeVisual guifg=#0D1421 guibg=#8F707D guisp=NONE blend=NONE gui=NONE
highlight MiniSurround guifg=#5E6473 guibg=#8F707D guisp=NONE blend=NONE gui=NONE
highlight MiniTablineCurrent guifg=#9EA2A9 guibg=#5E6473 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineFill guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniTablineHidden guifg=#B6585A guibg=#5E6473 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineModifiedCurrent guifg=#C2C4C7 guibg=#5E6473 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineModifiedHidden guifg=#7B818E guibg=#5E6473 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineModifiedVisible guifg=#C2C4C7 guibg=#5E6473 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineVisible guifg=#9EA2A9 guibg=#5E6473 guisp=NONE blend=NONE gui=NONE
highlight MiniTestEmphasis guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniTestFail guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniTestPass guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniTrailspace guifg=#53586E guibg=#C2C4C7 guisp=NONE blend=NONE gui=NONE
highlight ModeMsg guifg=#B6585A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MoreMsg guifg=#B6585A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight NonText guifg=#9EA2A9 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Number guifg=#8F707D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Operator guifg=#C2C4C7 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight PMenu guifg=#C2C4C7 guibg=#5E6473 guisp=NONE blend=NONE gui=NONE
highlight PMenuSel guifg=#C2C4C7 guibg=#3A6D83 guisp=NONE blend=NONE gui=NONE
highlight PmenuSbar guifg=#7B818E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight PmenuThumb guifg=#C2C4C7 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight PreProc guifg=#BA7E7D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Question guifg=#3A6D83 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Repeat guifg=#BA7E7D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Search guifg=#9EA2A9 guibg=#BA7E7D guisp=NONE blend=NONE gui=NONE
highlight! link MiniTablineTabpagesection Search
highlight SignColumn guifg=#7B818E guibg=#0D1421 guisp=NONE blend=NONE gui=NONE
highlight Special guifg=#6C8699 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight SpecialChar guifg=#555C72 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight SpecialKey guifg=#9EA2A9 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight SpellBad guifg=#53586E guibg=NONE guisp=#53586E blend=NONE gui=underline
highlight SpellCap guifg=#BA7E7D guibg=NONE guisp=#BA7E7D blend=NONE gui=underline
highlight SpellLocal guifg=#6C8699 guibg=NONE guisp=#6C8699 blend=NONE gui=underline
highlight SpellRare guifg=#9E83C9 guibg=NONE guisp=#9E83C9 blend=NONE gui=underline
highlight Statement guifg=#53586E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight StatusLine guifg=#C2C4C7 guibg=#5E6473 guisp=NONE blend=NONE gui=NONE
highlight StatusLineNC guifg=#7B818E guibg=#5E6473 guisp=NONE blend=NONE gui=NONE
highlight StatusLineTerm guifg=#B6585A guibg=#B6585A guisp=NONE blend=NONE gui=NONE
highlight StatusLineTermNC guifg=#BA7E7D guibg=#5E6473 guisp=NONE blend=NONE gui=NONE
highlight StorageClass guifg=#BA7E7D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight String guifg=#B6585A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Structure guifg=#9E83C9 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight TabLine guifg=#9EA2A9 guibg=#5E6473 guisp=NONE blend=NONE gui=NONE
highlight TabLineFill guifg=#9EA2A9 guibg=#5E6473 guisp=NONE blend=NONE gui=NONE
highlight TabLineSel guifg=#B6585A guibg=#5E6473 guisp=NONE blend=NONE gui=NONE
highlight Tag guifg=#BA7E7D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Title guifg=#3A6D83 guibg=NONE guisp=NONE blend=NONE gui=bold
highlight Todo guifg=#BA7E7D guibg=#5E6473 guisp=NONE blend=NONE gui=NONE
highlight TooLong guifg=#53586E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Type guifg=#BA7E7D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Typedef guifg=#BA7E7D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Underlined guifg=#53586E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight VertSplit guifg=#C2C4C7 guibg=#0D1421 guisp=NONE blend=NONE gui=NONE
highlight! link WinSeparator VertSplit
highlight Visual guifg=#0D1421 guibg=#7B818E guisp=NONE blend=NONE gui=NONE
highlight VisualNOS guifg=#53586E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight WarningMsg guifg=#53586E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight WildMenu guifg=#C2C4C7 guibg=#3A6D83 guisp=NONE blend=NONE gui=NONE
highlight WinBar guifg=#C2C4C7 guibg=#0D1421 guisp=NONE blend=NONE gui=NONE
highlight WinBarNC guifg=#7B818E guibg=#0D1421 guisp=NONE blend=NONE gui=NONE
highlight gitCommitOverflow guifg=#53586E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight gitCommitSummary guifg=#B6585A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight helpCommand guifg=#BA7E7D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight helpExample guifg=#BA7E7D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @attribute guifg=#3A6D83 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @boolean guifg=#3A6D83 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @character guifg=#BA7E7D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @character.special guifg=#555C72 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @comment guifg=#C2C4C7 guibg=NONE guisp=NONE blend=NONE gui=italic
highlight @conditional guifg=#53586E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constant guifg=#53586E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constant.builtin guifg=#53586E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constant.macro guifg=#53586E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constructor guifg=#C2C4C7 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @debug guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @define guifg=#9E83C9 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @exception guifg=#53586E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @field guifg=#B6585A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @float guifg=#3A6D83 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @function guifg=#3A6D83 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @function.builtin guifg=#53586E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @function.macro guifg=#53586E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @include guifg=#6C8699 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @keyword guifg=#9E83C9 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @keyword.function guifg=#6C8699 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @keyword.operator guifg=#9E83C9 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @label guifg=#6C8699 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @method guifg=#3A6D83 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @namespace guifg=#3A6D83 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @none guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @number guifg=#3A6D83 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @operator guifg=#C2C4C7 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @parameter guifg=#BA7E7D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @preproc guifg=#BA7E7D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @property guifg=#BA7E7D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @punctuation.bracket guifg=#C2C4C7 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @punctuation.delimiter guifg=#C2C4C7 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @punctuation.special guifg=#6C8699 guibg=NONE guisp=NONE blend=NONE gui=bold
highlight @repeat guifg=#53586E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @storageclass guifg=#BA7E7D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string guifg=#3A6D83 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string.escape guifg=#B6585A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string.regex guifg=#B6585A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string.special guifg=#555C72 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @symbol guifg=#6C8699 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @tag guifg=#BA7E7D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @tag.attribute guifg=#6C8699 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @tag.delimiter guifg=#6C8699 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text guifg=#B6585A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.bold guifg=#BA7E7D guibg=NONE guisp=NONE blend=NONE gui=bold
highlight @text.danger guifg=#53586E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.diff.add guifg=#B6585A guibg=#5E6473 guisp=NONE blend=NONE gui=bold
highlight @text.diff.delete guifg=#53586E guibg=#5E6473 guisp=NONE blend=NONE gui=bold
highlight @text.emphasis guifg=#9E83C9 guibg=NONE guisp=NONE blend=NONE gui=italic
highlight @text.environment guifg=#53586E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.environment.name guifg=#BA7E7D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.literal guifg=#B6585A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.math guifg=#6C8699 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.note guifg=#6C8699 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.reference guifg=#53586E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.strike guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=strikethrough
highlight @text.title guifg=#3A6D83 guibg=NONE guisp=NONE blend=NONE gui=bold
highlight @text.todo guifg=#BA7E7D guibg=#5E6473 guisp=NONE blend=NONE gui=NONE
highlight @text.underline guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=underline
highlight @text.uri guifg=NONE guibg=#5E6473 guisp=NONE blend=NONE gui=underline
highlight @type guifg=#3A6D83 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @type.builtin guifg=#3A6D83 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @type.definition guifg=#BA7E7D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @variable guifg=#BA7E7D guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @variable.builtin guifg=#53586E guibg=NONE guisp=NONE blend=NONE gui=NONE
