;:set syn=dosini

[colors]
; Inheriting colors from pywal via Xresources 
bg    = ${xrdb:color0}
fg    = ${xrdb:color7}
modfg = ${xrdb:color3}
alt   = ${xrdb:color2}
warn  = ${xrdb:color1}

[bar/default]
width = 100%
height = 30
radius = 5
fixed-center = true
wm-restack = i3

background = ${colors.bg}
foreground = ${colors.modfg}

padding-left = 2
padding-right = 2
module-margin = 3

font-0 = Iosevka Nerd Font:size=11;3

modules-left   = battery cpu memory vpn updates
modules-center = date
modules-right  = mpd i3 menu0

; --- WM & Navigation ---
[module/i3]
type = internal/i3
index-sort = true
format = <label-mode> <label-state>

label-focused = %index%
label-focused-padding = 1
label-focused-foreground = ${colors.bg}
label-focused-background = ${colors.modfg}

label-unfocused = %index%
label-unfocused-padding = 1

label-urgent = %index%
label-urgent-background = ${colors.alt}
label-urgent-padding = 1

; --- Networking ---
[module/vpn]
type = custom/script
exec = ~/.config/polybar/vpn-status.sh
interval = 5
label = "%output%"

[module/updates]
type = custom/script
exec = checkupdates | wc -l
interval = 600
label  = " %output%"

; --- X220 Hardware ---
[module/battery]
type = internal/battery
battery = BAT0
adapter = AC
full-at = 100

format-charging = <animation-charging> <label-charging>
format-charging-underline = ${colors.alt}
format-discharging = <ramp-capacity> <label-discharging>
format-discharging-underline = ${colors.modfg}

format-full =   <label-full>
format-full-underline = ${self.format-charging-underline}
format-full-overline = ${self.format-charging-underline}
format-full-padding = 1

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-framerate = 750

[module/cpu]
type = internal/cpu
interval = 2
label = " %percentage%%"

[module/memory]
type = internal/memory
interval = 2
label = " %percentage_used%%"

; --- System & Time ---
[module/date]
type = internal/date
interval = 5
date = %b/%d/%y   %H:%M
date-alt = %A   %H:%M 

[module/menu0]
type = custom/menu
format-padding = 1
label-open = 
label-close = 
menu-0-0 = "Shutdown"
menu-0-0-exec = shutdown now
menu-0-1 = "Restart"
menu-0-1-exec = reboot

; --- Media ---
[module/mpd]
type = internal/mpd
host = localhost
port = 6600
format-online = <label-song>
label-song = " %artist% - %title%"
label-song-maxlen = 40
label-offline = ""

; vim:ft=dosini
